Rib 161 implement user profile page
MatejFrnka/rate-it pull request #117
Opened 2024-01-31 17:43 UTC by vdrfg

### RIB-161: Implementation of User's Profile

- User can access his profile from top bar menu.
- Endpoint takes username for now since they are unique and ignore cases and other users can easily "search" for a user.
- Default message for user bio.
- User can add a bio/description by clicking into the field. Default message disappears. Text is saved when clicked away. 
- Follow button follows user and dynamically changes the follower count.
- Follow button is not visible for anonymous users and for users on their own profile.
- Page loads all interests with ratings from user, sorted by number of total likes.
- Interest can be extended by click and shows up to 3 best rated places, "Details" button will lead to separate page that lists all places.
- Page dynamically changes according to screen size.
- Small screens have slightly different positioning of Follow and Details buttons.

![image](https://github.com/MatejFrnka/rate-it/assets/137323658/c0dd3080-ae49-48e4-9cd0-cafe92bdf921)
![image](https://github.com/MatejFrnka/rate-it/assets/137323658/02c373b3-1847-4a1a-ab33-bce9df6303e6)
![image](https://github.com/MatejFrnka/rate-it/assets/137323658/cf11d7e6-4c1b-4410-98bb-4f869c7677ff)
![image](https://github.com/MatejFrnka/rate-it/assets/137323658/c46b46c5-8c81-4fda-84e2-578204e0f13b)
![image](https://github.com/MatejFrnka/rate-it/assets/137323658/74fa493f-4fe5-4234-b321-64c4e425656c)

2024-01-31 19:22 UTC, marthubner commented
<img width="1132" alt="image" src="https://github.com/MatejFrnka/rate-it/assets/86839034/cf0bbd86-c44a-4310-9bf6-1098ca8cb9b6">
There's an error in javascript when user is viewing his own profile

2024-01-31 19:26 UTC, marthubner commented on src/main/java/it/rate/webapp/services/RatingService.java
> +  }
This should probably be distributed to multiple smaller methods and possibly even services but we can do it later.

2024-01-31 19:26 UTC, marthubner commented on src/main/java/it/rate/webapp/services/RatingService.java
> +                  userRatedPlaceDTOs);
There is a constructor for this that takes in an interest and is not used

2024-01-31 19:26 UTC, marthubner commented on src/main/java/it/rate/webapp/services/RatingService.java
> +                                userRatingDTOs);
Constructor which takes place can be made to make this a bit shorter

2024-01-31 19:26 UTC, marthubner commented on src/main/resources/static/scripts/userBioEdit.js
> +    const maxBioLength = 150;
this should not be hardcoded

2024-02-01 14:37 UTC, MatejFrnka requested changes

2024-02-01 14:37 UTC, MatejFrnka commented on src/main/java/it/rate/webapp/services/RatingService.java
> +            interest ->
refactor

2024-02-01 14:42 UTC, MatejFrnka approved these changes

2024-02-01 16:53 UTC, marthubner approved these changes

2024-02-02 10:52 UTC, BenediktVitek approved these changes

2024-02-02 12:17 UTC, dondowoldo requested changes
Looks good and not sure if this is supposed to be a part of this pull request, but with the user profile implemented, i would like the user instances to be clickable across our website and redirecting to the users page. I think this would be for "Manage Users" and "Applications" in Interest Admin panel.

Also user for example can currently create an account with a username "signup" and nobody will ever see his profile 🤣 Maybe we need to have a look at that as well.

2024-02-02 13:21 UTC, merged