Rib 81 implement login and registration page
MatejFrnka/rate-it pull request #64
Opened 2024-01-17 10:18 UTC by VladislavChval

2024-01-17 11:08 UTC, dondowoldo requested changes
Things that need to be changed : 
- Maybe merge develop branch into this branch so fragments can be used on the header
- Remove "type=text" as per comment
- Looks fine on full resolution PC, but on mobile header is squished and cards not centered
- Maybe slightly larger cards. They take about 50% of mobile screen now and the fields seem really really small. At least on my device.
- Create separate JS file for the script and just link it in the html

2024-01-17 14:43 UTC, MatejFrnka approved these changes

2024-01-17 14:46 UTC, MatejFrnka approved these changes
fix the duplicated type, rebase to the latest updates by doing:

To be able to use fragments, do this:
git checkout develop
git pull
git checkout %this branch%
git rebase develop

2024-01-22 19:01 UTC, vdrfg commented
- Reworked design
- Icons still missing
- Login doesn't work for some reason

2024-01-23 16:26 UTC, marthubner requested changes

2024-01-23 16:26 UTC, marthubner commented on src/main/resources/templates/user/loginForm.html
> +</head>
The head is missing favicon and the title should probably be "Login | Ratespot" to be consistent with the other pages.
Maybe try to use our predefined fragment.

2024-01-23 16:26 UTC, marthubner commented on src/main/resources/templates/user/signupForm.html
> +</head>
The head is missing favicon and also the title should not be login.
Maybe try to use our predefined fragment.

2024-01-23 17:35 UTC, marthubner approved these changes

2024-01-24 09:49 UTC, dondowoldo approved these changes

2024-01-24 11:10 UTC, merged