Rib 113 change design of like button
MatejFrnka/rate-it pull request #66
Opened 2024-01-17 16:03 UTC by marthubner

### RIB-113: Change design of like button

- changing like button to outline when interest is not liked, unifying the color for both states

2024-01-17 17:41 UTC, vdrfg requested changes

2024-01-17 17:41 UTC, vdrfg commented on src/main/resources/templates/fragments.html
> +            <i class="fa-regular fa-heart"></i>
The classes shouldn't be changed due to related javascript.

2024-01-18 11:34 UTC, MatejFrnka approved these changes

2024-01-18 12:22 UTC, dondowoldo approved these changes

2024-01-18 12:28 UTC, merged