RIB-119: change /api/v1/interests/suggestions to POST, change index.j…
MatejFrnka/rate-it pull request #71
Opened 2024-01-18 19:41 UTC by marthubner

### RIB-119: Interests in main page loading ordered by distance

- when the main page is first loaded, it waits for the user to allow or deny access to their location, then the interests are loaded from the REST endpoint either as before or sorted by distance from the interest with the closest place.

2024-01-18 20:19 UTC, vdrfg approved these changes

2024-01-18 23:12 UTC, dondowoldo approved these changes

2024-01-21 17:36 UTC, MatejFrnka requested changes

2024-01-21 17:36 UTC, MatejFrnka commented on src/main/java/it/rate/webapp/controllers/api/InterestRestController.java
> +  @PostMapping("/suggestions")
Should this really be POST mapping? 
https://www.restapitutorial.com/lessons/httpmethods.html

2024-01-22 22:45 UTC, closed without merging